/** @type {Record<string, { label: string, packs: Record<string, Pack> }>} */
export const PRICING_BY_BEDROOM = {
  studio: {
    label: "Studio/Dorm",
    packs: {
      light: {
        id: "light",
        name: "Light Pack",
        icon: "📦",
        boxes: 15,
        dollies: 1,
        packingPaperLbs: 1.5,
        weekly: 75,
        additionalWeek: 38,
      },
      standard: {
        id: "standard",
        name: "Standard Pack",
        icon: "📦📦",
        boxes: 20,
        dollies: 1,
        packingPaperLbs: 2,
        weekly: 89,
        additionalWeek: 44,
      },
      heavy: {
        id: "heavy",
        name: "Heavy Pack",
        icon: "📦📦📦",
        boxes: 25,
        dollies: 1,
        packingPaperLbs: 2.5,
        weekly: 107,
        additionalWeek: 55,
      },
    },
  },
  "1": {
    label: "1 Bedroom",
    packs: {
      light: {
        id: "light",
        name: "Light Pack",
        icon: "📦",
        boxes: 25,
        dollies: 1,
        packingPaperLbs: 2.5,
        weekly: 107,
        additionalWeek: 55,
      },
      standard: {
        id: "standard",
        name: "Standard Pack",
        icon: "📦📦",
        boxes: 30,
        dollies: 1,
        packingPaperLbs: 3,
        weekly: 126,
        additionalWeek: 63,
      },
      heavy: {
        id: "heavy",
        name: "Heavy Pack",
        icon: "📦📦📦",
        boxes: 35,
        dollies: 1,
        packingPaperLbs: 3.5,
        weekly: 144,
        additionalWeek: 72,
      },
    },
  },
  "2": {
    label: "2 Bedrooms",
    packs: {
      light: {
        id: "light",
        name: "Light Pack",
        icon: "📦",
        boxes: 35,
        dollies: 1,
        packingPaperLbs: 3.5,
        weekly: 144,
        additionalWeek: 72,
      },
      standard: {
        id: "standard",
        name: "Standard Pack",
        icon: "📦📦",
        boxes: 40,
        dollies: 1,
        packingPaperLbs: 4,
        weekly: 162,
        additionalWeek: 81,
      },
      heavy: {
        id: "heavy",
        name: "Heavy Pack",
        icon: "📦📦📦",
        boxes: 45,
        dollies: 1,
        packingPaperLbs: 4.5,
        weekly: 179,
        additionalWeek: 90,
      },
    },
  },
  "3": {
    label: "3 Bedrooms",
    packs: {
      light: {
        id: "light",
        name: "Light Pack",
        icon: "📦",
        boxes: 45,
        dollies: 2,
        packingPaperLbs: 4.5,
        weekly: 179,
        additionalWeek: 90,
      },
      standard: {
        id: "standard",
        name: "Standard Pack",
        icon: "📦📦",
        boxes: 50,
        dollies: 2,
        packingPaperLbs: 5,
        weekly: 195,
        additionalWeek: 97,
      },
      heavy: {
        id: "heavy",
        name: "Heavy Pack",
        icon: "📦📦📦",
        boxes: 55,
        dollies: 2,
        packingPaperLbs: 5.5,
        weekly: 212,
        additionalWeek: 106,
      },
    },
  },
  "4": {
    label: "4 Bedrooms",
    packs: {
      light: {
        id: "light",
        name: "Light Pack",
        icon: "📦",
        boxes: 60,
        dollies: 2,
        packingPaperLbs: 6,
        weekly: 221,
        additionalWeek: 110,
      },
      standard: {
        id: "standard",
        name: "Standard Pack",
        icon: "📦📦",
        boxes: 70,
        dollies: 2,
        packingPaperLbs: 7,
        weekly: 249,
        additionalWeek: 124,
      },
      heavy: {
        id: "heavy",
        name: "Heavy Pack",
        icon: "📦📦📦",
        boxes: 80,
        dollies: 2,
        packingPaperLbs: 8,
        weekly: 276,
        additionalWeek: 138,
      },
    },
  },
  "5plus": {
    label: "5+ Bedrooms",
    packs: {
      light: {
        id: "light",
        name: "Light Pack",
        icon: "📦",
        boxes: 80,
        dollies: 2,
        packingPaperLbs: 10,
        weekly: 276,
        additionalWeek: 138,
      },
      standard: {
        id: "standard",
        name: "Standard Pack",
        icon: "📦📦",
        boxes: 100,
        dollies: 2,
        packingPaperLbs: 10,
        weekly: 329,
        additionalWeek: 164,
      },
      heavy: {
        id: "heavy",
        name: "Heavy Pack",
        icon: "📦📦📦",
        boxes: 120,
        dollies: 2,
        packingPaperLbs: 10,
        weekly: 384,
        additionalWeek: 142,
      },
    },
  },
};

export const BOX_DIMENSIONS = '31" x 21" x 23.5"';
export const DEFAULT_PACK_ID = "standard";
